### ISSUE TITLE
Error applying FixMiner patches to ManyBugs programs

### ISSUE THREAD

**Issue by bstee615** [TruX-DTF/fixminer_source#17]
Hello, my name is Ben Steenhoek. I’m part of a software engineering research lab at Iowa State University. My team and I would like to use your tool to repair C programs as part of an application of our current research work.

Thank you for your code release. I am trying to use FixMiner to repair bugs in ManyBugs. I was able to mine patches for C programs, and use your ManyBugs integration to apply patches, but most patches fail because of concrete identifiers included in the patch. I'm not sure whether this is expected behavior or due to my own error. Can you provide instructions for using the tool to repair ManyBugs?

Here is an overview of the steps I followed to set up the tool:
1. Install Redis, spinfer, and coccinelle
2. Start Redis server at port `6399`
3. Run `dataset4c` to generate a dataset of C projects
4. Run `richedit`, `actionSI`, `compare`, `cluster`, `tokenSI`, `compare`, `stats`, `patterns`, `indexClusters` to prepare coccinelle patches
5. Run `manybugs` to export ManyBugs projects
6. Run `patchManyBugs` to patch the exported ManyBugs projects

I ran the final step with this command: `bash fixminer.sh src/main/resources/config.yml patchManyBugs`. I applied a few minor patches to correct filepaths which were required for the patching to work. I've attached the log from running the command here: [app.log](https://github.com/SerVal-DTF/fixminer_source/files/6184176/app.log).

Here is an example of a patch which was skipped due to the error:
```
2021-03-22 12:21:52,842 - 2785884 - DEBUG - commons.py:shellGitCheckout - /home/benjis/work/tools/fixminer_source/spinfer/statics/spatch --sp-file /home/benjis/work/tools/fixminer_source/fixminer-data/patches/cocci/MethodDeclaration_5_1.cocci2 /home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/diffs/epan/reassemble.c-37122 --patch -o/home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/patches/reassemble.c-37122 > /home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/patches/reassemble.c-37122MethodDeclaration_5_1.cocci2.txt	
2021-03-22 12:21:52,842 - 2785884 - DEBUG - commons.py:shellGitCheckout - /home/benjis/work/tools/fixminer_source/spinfer/statics/spatch --sp-file /home/benjis/work/tools/fixminer_source/fixminer-data/patches/cocci/MethodDeclaration_5_1.cocci2 /home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/diffs/epan/reassemble.c-37122 --patch -o/home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/patches/reassemble.c-37122 > /home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/patches/reassemble.c-37122MethodDeclaration_5_1.cocci2.txt	init_defs_builtins: /vol/helium/benjis/tools/fixminer_source/spinfer/statics/standard.h
(ONCE) Expected tokens maybe_optimize_method_call
Skipping: /home/benjis/work/tools/fixminer_source/fixminer-data/manybugs/manybugs:wireshark:37122-37123/diffs/epan/reassemble.c-37122
```

Here is the cocci patch it's trying to apply:
```
@@
expression E0, E1;
@@
- if (maybe_optimize_method_call(E0, E1) > 0)  
+ int ret = maybe_optimize_method_call(E0, E1); 
+ if (ret >= 0)  
  {
- return 1; 
+ return ret; 
  }
// Infered from: (cpython/{prevFiles/prev_97f5de_93e801_Python#compile.c,revFiles/97f5de_93e801_Python#compile.c}: compiler_call)
// Recall: 0.05, Precision: 1.00, Matching recall: 1.00

// ---------------------------------------------
```

All of the patches fail with a similar problem, where the cocci patch contains concrete identifiers which are specific to the source project and so cannot be applied to other projects. Any help would be much appreciated.

**Comment by anilkoyuncu** [comment]
Hello Ben. Thank you for your interested in my work. I am glad that you were able to run the code. From what i see from the information you provided the code seems to be working as expected. Historically I designed the fixminer project for java, where the objective is to automatically mine fix pattern that can be used in program repair. However, as I highlighted in the fixminer paper (https://arxiv.org/abs/1810.01791), the transfer of the fix patterns must be done manually. 

In order to overcome this limitation I started working on another project called FlexiRepair (https://arxiv.org/abs/2011.13280, https://github.com/FlexiRepair). 
The idea is to leverage fixminer as miner, then leverage other tools such as spinfer and coccinelle to perform automated transfer of the fix patterns. 

Regarding to your issue, i see two possible solutions:
i) You can skip the steps in fixminer_source that are designed for FlexiRepair and implement patterns manually that are produced in step 9. patterns. In this case you will not have concrete identifiers, but you need to implement an engine to match the patterns and transform source code.

ii) You can try the FlexiRepair way from the link corresponding repository (https://github.com/FlexiRepair). Please note that in FlexiRepair I really on coccinelle to match and transform the fix patterns. And for most the case you may have fix patterns that are very specific. This is a desired behaviour. Because, in contrast to FixMiner, with coccinelle we need concrete identifier to perform changes. 

Let me know if you need further clarifications.

**Comment by bstee615** [comment]
Thank you for the detailed response! Ok, now I understand the limitation. I'll try to use FlexiRepair.
